name: "Module Test"
on: [push, pull_request]

permissions: read-all

jobs:
  terraform-plan:
    name: "Terraform Lint and Plan"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.4

      - uses: terraform-docs/gh-actions@v1.0.0

      - uses: dflook/terraform-fmt@v1

      - uses: bridgecrewio/checkov-action@v12

      - uses: terraform-linters/setup-tflint@v3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color 2>&1